export const env = {
    SITE_NAME: process.env.SITE_NAME || 'Pride 2025',
    COMPANY_NAME: process.env.COMPANY_NAME || 'Pride Amsterdam',
    SHOPIFY_STORE_DOMAIN: process.env.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN,
    SHOPIFY_STOREFRONT_TOKEN: process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_TOKEN,
    SHOPIFY_API_VERSION: process.env.NEXT_PUBLIC_SHOPIFY_GRAPHQL_API_VERSION || '2024-01'
  } as const;